const labels = {
  dashboard: {
    'homeHeading': 'Importance of Home Cleanliness in India and Benefits of Using Phenyl',
    'homeDescription': 'In India, maintaining home cleanliness is essential for a healthy and hygienic lifestyle, especially in densely populated areas where dust, germs, and bacteria can accumulate quickly. Poor home sanitation contributes to the spread of diseases like diarrhea, dengue, and respiratory infections. A clean home environment promotes physical well-being, mental peace, and a better quality of life. Regular cleaning with effective disinfectants like phenyl not only removes dirt but also kills harmful microbes lingering on floors and surfaces. Phenyl leaves behind a pleasant fragrance, creating a refreshing atmosphere. Its powerful cleaning properties help prevent infections and reduce allergen buildup, particularly important for children and the elderly. In Indian households, where barefoot walking indoors is common, sanitized floors are crucial. Using trusted home cleaners ensures a safe, germ-free living space for the entire family.',
    'toiletHeading': 'Toilet Cleanliness in India and the Importance of Using Toilet Cleaners',
    'toiletDescription': 'Maintaining toilet cleanliness is crucial for improving public health and hygiene in India. In many regions, poor sanitation practices lead to the spread of harmful diseases like cholera, diarrhea, and urinary infections. Dirty toilets can also become breeding grounds for flies, mosquitoes, and harmful bacteria, posing serious health risks. Regular cleaning with a quality toilet cleaner helps eliminate stains, kill germs, and prevent bad odors. Toilet cleaners are specially formulated to remove tough deposits and disinfect surfaces effectively. Using them ensures a hygienic and pleasant environment for every household. Clean toilets contribute to the dignity, safety, and well-being of families, especially women and children. Promoting toilet hygiene is essential for building a cleaner, healthier, and more respectful India.',
    'handwashHeading': 'The Hidden Risk: Not Washing Hands Before Meals',
    'handwashDescriptin': 'In many parts of India, especially in rural and semi-urban areas, the practice of washing hands with proper handwash before eating is still not widely followed. People often rinse their hands with plain water, unaware that this does not effectively remove harmful bacteria and viruses. This lack of proper hygiene contributes significantly to the spread of foodborne illnesses, diarrhoea, typhoid, and intestinal infections—especially among children. According to UNICEF, poor hand hygiene is a leading cause of preventable diseases in India. Encouraging the use of handwash before meals can drastically reduce health risks, improve community well-being, and build a healthier future.',
    'bleachTitle': 'Powerful Protection with Bleaching Powder - For a Cleaner, Germ-Free Environment',
    'bleachDesc': 'Bleaching powder is a powerful disinfectant and cleaning agent widely used in homes, hospitals, and public places. Known for its strong germ-killing properties, it effectively eliminates bacteria, viruses, and fungi from surfaces. Commonly used for sanitizing floors, toilets, and drainage areas, it also helps in water purification and odor control. Just a small quantity of bleaching powder mixed with water can make surfaces visibly cleaner and safer. Whether you are maintaining hygiene in your home or ensuring sanitation in public spaces, bleaching powder is a reliable, affordable solution for everyday cleanliness and disinfection.'
  },
  product: {},
  about: {},
  contact: {},
};
export default labels;